in_channels : 3
num_classes : 10
lr : 0.1
weight_decay : 0.001
epochs : 160
batch_size : 128
norm : 0.2
lamb : 1.2
rho : 1.02
freq : 1
backbone : 'vgg'
optimizer : 'sgd'
momentum : 0
scheduler : 'cos'
pca_dim : 10
num_classes_sub : 10
cutmix: 1
cutmix_prob: 0.5