in_channels : 3
num_classes : 10
lr : 0.01
weight_decay : 0.0005
batch_size : 128
epochs : 180
norm : 0.2
lamb : 1.2
freq : 1
rho : 1.02
backbone : 'res18'
optimizer : 'sgd'
momentum : 0.9
scheduler : 'cos'
pca_dim : 10
num_classes_sub : 10
cutmix: 1
cutmix_prob: 0.5