in_channels : 1
num_classes : 10
lr : 0.01
weight_decay : 0.001
epochs : 50
batch_size : 128
norm : 0.1
lamb : 1.2
rho : 1.2
freq : 1
backbone : 'conv2'
optimizer : 'sgd'
momentum : 0.9
scheduler : 'cos'
pca_dim : 10
num_classes_sub : 10
cutmix: 0